version: '3.8'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: YoutWi
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
    ports:
      - "8080:80"
    depends_on:
      - db

  neo4j:
    image: neo4j:latest
    restart: always
    environment:
      NEO4J_AUTH: neo4j/${NEO4J_PASSWORD}
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
      - neo4j-import:/var/lib/neo4j/import
      - neo4j-plugins:/plugins

  app:
    build:
      context: ./YoutWiBackend
    restart: always
    ports:
      - "4430:443"
    environment:
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_SECURE: "false"
      SMTP_USER: joelhernandezmartin01@gmail.com
      SMTP_PASS: ${SMTP_PASS}
      SMTP_FROM: "YoutWi"
      GOOGLE_CLIENT_ID: "664005080480-vsbs8jd9pgj1tvt4tsgpikol2sat4ld1.apps.googleusercontent.com"
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: ${NEO4J_PASSWORD}
      FRONTEND_URL: https://${SERVER_HOST}:443
      JWT_SECRET: moiseshijodeputa
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: YoutWi
      TWITCH_CLIENT_ID: ynw6ywjz5wvdnz0q4egw1dzmjxhtkj
      TWITCH_CLIENT_SECRET: ${TWITCH_CLIENT_SECRET}
    depends_on:
      - db
      - neo4j

volumes:
  db-data:
  neo4j-data:
  neo4j-logs:
  neo4j-import:
  neo4j-plugins:
